# Generated by Django 4.2.7 on 2023-11-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('continent', models.CharField(max_length=30, verbose_name='Континент')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('students_quantity', models.IntegerField(verbose_name='Количество студентов')),
                ('built_in', models.IntegerField(verbose_name='Год основания')),
                ('test_type', models.CharField(max_length=30, verbose_name='Тип теста по английскому языку')),
                ('test_score', models.IntegerField(verbose_name='Требуемый балл')),
                ('acceptance_age', models.IntegerField(verbose_name='Возраст')),
                ('live_type', models.CharField(max_length=30, verbose_name='Тип проживания')),
                ('faculty_quantity', models.IntegerField(verbose_name='Количество факультетов')),
                ('body', models.TextField()),
            ],
        ),
    ]
