# Generated by Django 4.2.7 on 2023-11-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='short_detail',
            field=models.CharField(default='asasasa', max_length=150, verbose_name='Краткие подробности'),
            preserve_default=False,
        ),
    ]
