# Generated by Django 4.2.6 on 2023-11-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_article',
            field=models.BooleanField(default=False),
        ),
    ]
