# Generated by Django 4.2.6 on 2023-12-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_main_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article_image',
            field=models.ImageField(upload_to='blog_photos'),
        ),
    ]
