# Generated by Django 4.2.6 on 2023-12-18 04:44

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='blog_photos'),
        ),
    ]
